import {
  ParsedDesign,
  ParsedSection,
  ParsedElement,
  ParsedFont,
} from '../types/index';
import { toClassName } from '../utils/helpers';

// ─────────────────────────────────────────────────────────────
// Main CSS generation entry point
// ─────────────────────────────────────────────────────────────

export function generateCSS(
  desktopDesign: ParsedDesign,
  mobileDesign: ParsedDesign
): string {
  const allFonts  = mergeFonts(desktopDesign.fonts, mobileDesign.fonts);
  const allColors = mergeColorMaps(desktopDesign.colors, mobileDesign.colors);
  const primaryFont   = allFonts[0]?.family ?? 'sans-serif';
  const secondaryFont = allFonts[1]?.family ?? primaryFont;

  const blocks: string[] = [
    buildFileHeader(),
    buildImports(allFonts),
    buildReset(),
    buildCSSVariables(allColors, primaryFont, secondaryFont, desktopDesign),
    buildBaseStyles(primaryFont),
    ...buildSectionStyles(desktopDesign.sections, mobileDesign.sections),
    buildMobileMediaQuery(mobileDesign.sections, desktopDesign.sections),
  ];

  return blocks.filter(Boolean).join('\n\n');
}

// ─────────────────────────────────────────────────────────────
// File header
// ─────────────────────────────────────────────────────────────

function buildFileHeader(): string {
  const now = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  return `/* ============================================================
   style.css — Generated by Figma → HTML Generator
   Generated: ${now}
   ============================================================ */`;
}

// ─────────────────────────────────────────────────────────────
// @font-face (non-Google custom fonts)
// ─────────────────────────────────────────────────────────────

function buildImports(fonts: ParsedFont[]): string {
  const customFonts = fonts.filter((f) => !f.isGoogleFont);
  if (customFonts.length === 0) return '';

  const seen = new Set<string>();
  const declarations = customFonts
    .filter((f) => {
      if (seen.has(f.family)) return false;
      seen.add(f.family);
      return true;
    })
    .map((f) => {
      const family = f.family.replace(/\s+/g, '-').toLowerCase();
      return `@font-face {
  font-family: '${f.family}';
  src: url('../assets/fonts/${family}-${f.weight}.woff2') format('woff2'),
       url('../assets/fonts/${family}-${f.weight}.woff') format('woff');
  font-weight: ${f.weight};
  font-style: ${f.style};
  font-display: swap;
}`;
    });

  return declarations.join('\n\n');
}

// ─────────────────────────────────────────────────────────────
// Reset
// ─────────────────────────────────────────────────────────────

function buildReset(): string {
  return `/* ============================================================
   Reset & Base
   ============================================================ */

*,
*::before,
*::after { box-sizing: border-box; margin: 0; padding: 0; }

html { scroll-behavior: smooth; -webkit-text-size-adjust: 100%; }

body { overflow-x: hidden; }

img, video, svg { display: block; max-width: 100%; }

button { cursor: pointer; border: none; background: none; }

a { text-decoration: none; color: inherit; }

ul, ol { list-style: none; }`;
}

// ─────────────────────────────────────────────────────────────
// CSS custom properties
// ─────────────────────────────────────────────────────────────

function buildCSSVariables(
  colors: Map<string, string>,
  primaryFont: string,
  secondaryFont: string,
  design: ParsedDesign
): string {
  const colorEntries = Array.from(colors.entries()).slice(0, 20);
  const [primary, secondary, accent, ...rest] = colorEntries;

  const colorVars: string[] = [];
  if (primary)   colorVars.push(`  --color-primary:    ${primary[0]};`);
  if (secondary) colorVars.push(`  --color-secondary:  ${secondary[0]};`);
  if (accent)    colorVars.push(`  --color-accent:     ${accent[0]};`);
  rest.slice(0, 10).forEach(([hex], i) => {
    colorVars.push(`  --color-${i + 4}:         ${hex};`);
  });
  colorVars.push(`  --color-white: #ffffff;`);
  colorVars.push(`  --color-black: #000000;`);
  colorVars.push(`  --color-bg:    ${design.backgroundColor};`);

  return `:root {
${colorVars.join('\n')}

  --font-primary:   '${primaryFont}', sans-serif;
  --font-secondary: '${secondaryFont}', sans-serif;

  --transition-base: 250ms ease;
}`;
}

// ─────────────────────────────────────────────────────────────
// Base body styles
// ─────────────────────────────────────────────────────────────

function buildBaseStyles(primaryFont: string): string {
  return `/* ============================================================
   Base
   ============================================================ */

body {
  font-family: '${primaryFont}', sans-serif;
  font-size: 16px;
  line-height: 1.6;
  background-color: var(--color-bg);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`;
}

// ─────────────────────────────────────────────────────────────
// Section + element styles
// ─────────────────────────────────────────────────────────────

function buildSectionStyles(
  desktopSections: ParsedSection[],
  mobileSections: ParsedSection[]
): string[] {
  return desktopSections.map((section) => {
    const mobileSection = mobileSections.find(
      (m) => toClassName(m.name) === toClassName(section.name)
    );
    return buildSectionBlock(section, mobileSection);
  });
}

function buildSectionBlock(section: ParsedSection, _mobile?: ParsedSection): string {
  const sc = section.className;
  const lines: string[] = [
    `/* ============================================================\n   ${section.name}\n   ============================================================ */`,
    buildCssBlock(`.${sc}`, buildSectionBaseProps(section)),
  ];

  if (!section.isAutoLayout && section.width && section.height) {
    lines.push(buildCssBlock(`.${sc} .${sc}__inner`, {
      position:     'relative',
      width:        `${Math.round(section.width)}px`,
      'min-height': `${Math.round(section.height)}px`,
    }));
  }

  lines.push(...collectElementStyles(section.children, sc));

  return lines.filter(Boolean).join('\n\n');
}

function buildSectionBaseProps(section: ParsedSection): Record<string, string | undefined> {
  const props: Record<string, string | undefined> = {
    position: 'relative',
    width:    '100%',
    overflow: 'hidden',
  };

  if (section.backgroundColor)    props['background-color'] = section.backgroundColor;
  if (section.backgroundGradient) props['background']        = section.backgroundGradient;
  if (section.backgroundImage) {
    props['background-image']    = section.backgroundImage;
    props['background-size']     = 'cover';
    props['background-position'] = 'center';
    props['background-repeat']   = 'no-repeat';
  }
  const boxShadow = section.cssStyles['box-shadow'];
  if (boxShadow) props['box-shadow'] = boxShadow;

  if (section.isAutoLayout) {
    for (const [k, v] of Object.entries(section.cssStyles)) {
      if (k !== 'box-shadow') props[k] = v;
    }
    props['width'] = '100%';
  }

  return props;
}

function collectElementStyles(elements: ParsedElement[], sectionClass: string): string[] {
  const styles: string[] = [];
  for (const el of elements) {
    const selector = `.${sectionClass} .${sectionClass}__${el.className}`;
    const block = buildCssBlock(selector, buildElementProps(el));
    if (block) styles.push(block);
    if (el.children.length > 0) styles.push(...collectElementStyles(el.children, sectionClass));
  }
  return styles;
}

function buildElementProps(el: ParsedElement): Record<string, string | undefined> {
  // Parser already computed position/left/top/width/height/background/flex in cssStyles
  const props: Record<string, string | undefined> = { ...el.cssStyles };

  if (el.textNode) applyTextStyles(props, el.textNode);

  if (el.isImage) {
    props['object-fit']      = 'cover';
    props['object-position'] = 'center';
  }

  return props;
}

function applyTextStyles(
  props: Record<string, string | undefined>,
  tn: ParsedElement['textNode'] & object
): void {
  props['font-family'] = `'${tn.fontFamily}', sans-serif`;
  props['font-size']   = `${tn.fontSize}px`;
  props['font-weight'] = String(tn.fontWeight);
  props['line-height'] = tn.lineHeight;
  props['color']       = tn.color;
  props['text-align']  = tn.textAlign;
  if (tn.letterSpacing && tn.letterSpacing !== '0') props['letter-spacing'] = tn.letterSpacing;
  if (tn.textTransform  && tn.textTransform  !== 'none') props['text-transform']  = tn.textTransform;
  if (tn.textDecoration && tn.textDecoration !== 'none') props['text-decoration'] = tn.textDecoration;
}

// ─────────────────────────────────────────────────────────────
// Mobile media query overrides
// ─────────────────────────────────────────────────────────────

function buildMobileMediaQuery(
  mobileSections: ParsedSection[],
  desktopSections: ParsedSection[]
): string {
  const overrides: string[] = [];

  for (const mSection of mobileSections) {
    const dSection = desktopSections.find((d) => toClassName(d.name) === toClassName(mSection.name));
    if (!dSection) continue;
    overrides.push(...buildSectionMobileOverrides(mSection, dSection));
  }

  if (overrides.length === 0) return '';

  return `/* ============================================================
   Mobile overrides (< 768px) — from mobile Figma frame
   ============================================================ */

@media (max-width: 767px) {
${overrides.join('\n\n')}
}`;
}

function buildSectionMobileOverrides(mSection: ParsedSection, dSection: ParsedSection): string[] {
  const sc = mSection.className;
  const result: string[] = [];

  if (mSection.backgroundColor && mSection.backgroundColor !== dSection.backgroundColor) {
    result.push(`  .${sc} { background-color: ${mSection.backgroundColor}; }`);
  }

  for (const mel of flattenElements(mSection.children)) {
    const override = buildElementMobileOverride(mel, dSection, sc);
    if (override) result.push(override);
  }

  return result;
}

function buildElementMobileOverride(
  mel: ParsedElement,
  dSection: ParsedSection,
  sc: string
): string | undefined {
  if (!mel.textNode) return undefined;
  const dEl = findFlatElement(dSection.children, mel.className);
  if (!dEl?.textNode) return undefined;

  const mtn = mel.textNode;
  const dtn = dEl.textNode;
  const lines: string[] = [];
  if (mtn.fontSize    !== dtn.fontSize)    lines.push(`    font-size: ${mtn.fontSize}px;`);
  if (mtn.lineHeight  !== dtn.lineHeight)  lines.push(`    line-height: ${mtn.lineHeight};`);
  if (mtn.textAlign   !== dtn.textAlign)   lines.push(`    text-align: ${mtn.textAlign};`);

  return lines.length ? `  .${sc} .${sc}__${mel.className} {\n${lines.join('\n')}\n  }` : undefined;
}

// ─────────────────────────────────────────────────────────────
// CSS block builder
// ─────────────────────────────────────────────────────────────

function buildCssBlock(
  selector: string,
  styles: Record<string, string | undefined>
): string {
  const declarations = Object.entries(styles)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `  ${k}: ${v};`);

  if (declarations.length === 0) return '';

  return `${selector} {\n${declarations.join('\n')}\n}`;
}

// ─────────────────────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────────────────────

function mergeColorMaps(a: Map<string, string>, b: Map<string, string>): Map<string, string> {
  const result = new Map(a);
  for (const [hex, name] of b.entries()) {
    if (!result.has(hex)) result.set(hex, name);
  }
  return result;
}

function mergeFonts(a: ParsedFont[], b: ParsedFont[]): ParsedFont[] {
  const seen = new Set<string>();
  const result: ParsedFont[] = [];
  for (const f of [...a, ...b]) {
    const key = `${f.family}|${f.weight}|${f.style}`;
    if (!seen.has(key)) {
      seen.add(key);
      result.push(f);
    }
  }
  return result;
}

function flattenElements(els: ParsedElement[]): ParsedElement[] {
  const result: ParsedElement[] = [];
  for (const el of els) {
    result.push(el);
    if (el.children.length) result.push(...flattenElements(el.children));
  }
  return result;
}

function findFlatElement(els: ParsedElement[], className: string): ParsedElement | undefined {
  for (const el of els) {
    if (el.className === className) return el;
    if (el.children.length) {
      const found = findFlatElement(el.children, className);
      if (found) return found;
    }
  }
  return undefined;
}
