import { GeneratorConfig, ParsedAsset, ParsedFont } from '../types/index';
import { BOOTSTRAP_VERSION } from '../utils/config';
import dayjs from 'dayjs';

export function generateReadme(
  config: GeneratorConfig,
  desktopAssets: ParsedAsset[],
  mobileAssets: ParsedAsset[],
  fonts: ParsedFont[]
): string {
  const now = dayjs().format('DD MMMM YYYY');
  const allAssets = [...desktopAssets, ...mobileAssets];
  const imageAssets = allAssets.filter((a) => a.type === 'image' || a.type === 'illustration');
  const iconAssets  = allAssets.filter((a) => a.type === 'icon' || a.type === 'logo' || a.type === 'svg');

  const fontList = [...new Set(fonts.map((f) => f.family))];

  const assetTable = allAssets.length
    ? `| File Name | Type | Format | Dimensions | Source |\n|-----------|------|--------|------------|--------|\n` +
      allAssets.map((a) =>
        `| \`${a.fileName}\` | ${a.type} | ${a.targetFormat.toUpperCase()} | ${a.width}×${a.height}px | Figma |`
      ).join('\n')
    : '_No assets were downloaded._';

  return `# ${config.projectName}

> Auto-generated by **Figma → HTML Generator**
> Generated on: ${now}

---

## Project Structure

\`\`\`
${config.projectName}/
├── index.html          # Main HTML page
├── css/
│   └── style.css       # Custom stylesheet (section-scoped BEM classes)
├── js/
│   └── script.js       # Lightweight vanilla JS (if required)
├── assets/
│   ├── images/         # Raster images (WebP optimised)
│   ├── icons/          # SVG icons and logos
│   └── fonts/          # Custom font files (if self-hosted)
└── README.md
\`\`\`

---

## Dependencies

| Dependency | Version | CDN |
|------------|---------|-----|
| Bootstrap CSS | ${BOOTSTRAP_VERSION} | jsDelivr |
| Bootstrap JS Bundle | ${BOOTSTRAP_VERSION} | jsDelivr |
${fontList.map((f) => `| ${f} | Auto-detected | Google Fonts`).join('\n')}

All dependencies are loaded via CDN — no npm install required to run the output HTML.

---

## How to Run

1. Open \`index.html\` in any modern browser.
2. No build tools or local server required.
3. For development, a live-reload server is recommended:

\`\`\`bash
# Using VS Code Live Server extension (recommended)
# Right-click index.html → Open with Live Server

# Or using npx serve
npx serve .

# Or using Python
python -m http.server 8080
\`\`\`

---

## Responsive Breakpoints

| Breakpoint | Viewport | Layout |
|------------|----------|--------|
| Mobile Portrait  | ≤ 480px  | Mobile Figma design |
| Mobile Landscape | ≤ 575px  | Mobile Figma design |
| Tablet Portrait  | 576–767px | Adaptive |
| Tablet Landscape | 768–991px | Adaptive |
| Laptop           | 992–1199px | Desktop Figma design |
| Desktop          | 1200–1399px | Desktop Figma design |
| Large Desktop    | ≥ 1400px | Desktop Figma design |

---

## Assets Downloaded

### Images (${imageAssets.length})
${imageAssets.length ? imageAssets.map((a) => `- \`${a.relativePath}\` — ${a.width}×${a.height}px`).join('\n') : '_None_'}

### Icons & SVGs (${iconAssets.length})
${iconAssets.length ? iconAssets.map((a) => `- \`${a.relativePath}\``).join('\n') : '_None_'}

---

## Full Asset Table

${assetTable}

---

## Typography

${fontList.length
  ? fontList.map((f) => {
      const weights = [...new Set(fonts.filter((ff) => ff.family === f).map((ff) => ff.weight))].sort();
      const isGoogle = fonts.find((ff) => ff.family === f)?.isGoogleFont;
      return `- **${f}** — Weights: ${weights.join(', ')} — Source: ${isGoogle ? 'Google Fonts (CDN)' : 'Custom Font'}`;
    }).join('\n')
  : '_No fonts detected._'}

---

## Figma Sources

| Design | URL |
|--------|-----|
| Desktop | ${config.desktopUrl} |
| Mobile  | ${config.mobileUrl}  |

---

## CSS Architecture

All styles are **section-scoped** to prevent conflicts:

\`\`\`css
/* Each section has its own namespace */
.hero-section { }
.hero-section .hero-section__hero-content { }
.hero-section .hero-section__hero-title { }
.hero-section .hero-section__hero-description { }
.hero-section .hero-section__hero-btn { }

.features-section { }
.features-section .features-section__card { }
/* ...etc */
\`\`\`

---

## Bootstrap Version

This project uses **Bootstrap ${BOOTSTRAP_VERSION}** loaded via CDN.

The following Bootstrap utilities are used:
- Container / Row / Col grid system
- \`d-flex\`, \`align-items-*\`, \`justify-content-*\` flexbox utilities
- \`gap-*\` spacing utilities
- Responsive breakpoint classes (\`col-md-*\`, \`col-lg-*\`)
- \`navbar\`, \`navbar-expand-lg\`, \`navbar-toggler\` for responsive nav
- \`btn\`, \`btn-primary\`, \`btn-outline-primary\` for buttons
- \`text-center\`, \`mb-*\`, \`g-*\` utility classes

---

_Generated by Figma → HTML Generator v1.0.0_
`;
}

